name: interactive_country_map
description: "Add interactive map to your app and select any regions with a tap!"
version: 0.0.8
homepage: https://clementbeal.github.io/
repository: https://github.com/ClementBeal/interactive_country_map
issue_tracker: https://github.com/ClementBeal/interactive_country_map/issues

screenshots:
  - description: "Selection of a region of France to define the birthplace"
    path: doc/france_department.gif
  - description: "Repartition of some amimals in france"
    path: doc/france_animals.png

topics:
  - ui
  - map
  - chart
  - plot

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  http: ^1.2.1
  html: ^0.15.4
  recase: ^4.1.0
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - res/maps/
