enum MapEntity {
  africa("africa"),
  andorra("andorra"),
  angola("angola"),
  argentina("argentina"),
  armenia("armenia"),
  australia("australia"),
  austria("austria"),
  azerbaijan("azerbaijan"),
  bahamas("bahamas"),
  bahrain("bahrain"),
  bangladesh("bangladesh"),
  belarus("belarus"),
  belgium("belgium"),
  bhutan("bhutan"),
  bolivia("bolivia"),
  bosniaHerzegovina1("bosnia-herzegovina-1"),
  bosniaHerzegovina2("bosnia-herzegovina-2"),
  botswana("botswana"),
  brazil("brazil"),
  bruneiDarussalam("brunei-darussalam"),
  bulgaria("bulgaria"),
  burkinaFaso("burkina-faso"),
  burundi("burundi"),
  cambodia("cambodia"),
  cameroon("cameroon"),
  canada("canada"),
  capeVerde("cape-verde"),
  centralAfricanRepublic("central-african-republic"),
  chad("chad"),
  chile("chile"),
  chile2("chile-2"),
  china("china"),
  colombia("colombia"),
  congo("congo"),
  congoDr("congo-dr"),
  costaRica("costa-rica"),
  croatia("croatia"),
  cuba("cuba"),
  cyprus("cyprus"),
  czechRepublic("czech-republic"),
  denmark("denmark"),
  djibouti("djibouti"),
  dominicanRepublic("dominican-republic"),
  ecuador("ecuador"),
  egypt("egypt"),
  elSalvador("el-salvador"),
  estonia("estonia"),
  ethiopia("ethiopia"),
  faroeIslands("faroeIslands"),
  finland("finland"),
  france("france"),
  franceDepartments("france-departments"),
  franceNew("france-new"),
  georgia("georgia"),
  germany("germany"),
  greece("greece"),
  guatemala("guatemala"),
  guinea("guinea"),
  haiti("haiti"),
  honduras("honduras"),
  hongKong("hong-kong"),
  hungary("hungary"),
  iceland("iceland"),
  india("india"),
  indonesia("indonesia"),
  iran("iran"),
  iraq("iraq"),
  ireland("ireland"),
  israel("israel"),
  italy("italy"),
  ivoryCoast("ivory-coast"),
  jamaica("jamaica"),
  japan("japan"),
  kazakhstan("kazakhstan"),
  kenya("kenya"),
  kosovo("kosovo"),
  kyrgyzstan("kyrgyzstan"),
  laos("laos"),
  latvia("latvia"),
  liechtenstein("liechtenstein"),
  lithuania("lithuania"),
  luxembourg("luxembourg"),
  macedonia("macedonia"),
  malaysia("malaysia"),
  mali("mali"),
  malta("malta"),
  mexico("mexico"),
  moldova("moldova"),
  montenegro("montenegro"),
  morocco("morocco"),
  mozambique("mozambique"),
  myanmar("myanmar"),
  namibia("namibia"),
  nepal("nepal"),
  netherlands("netherlands"),
  newZealand("new-zealand"),
  nicaragua("nicaragua"),
  nigeria("nigeria"),
  norway("norway"),
  oman("oman"),
  pakistan("pakistan"),
  palestine("palestine"),
  panama("panama"),
  paraguay("paraguay"),
  peru("peru"),
  philippines("philippines"),
  poland("poland"),
  portugal("portugal"),
  portugalRegions("portugal-regions"),
  puertoRico("puerto-rico"),
  qatar("qatar"),
  romania("romania"),
  russia("russia"),
  rwanda("rwanda"),
  sanMarino("san-marino"),
  saudiArabia("saudi-arabia"),
  serbia("serbia"),
  serbiaWithoutKosovo("serbia-without-kosovo"),
  sierraLeone("sierra-leone"),
  singapore("singapore"),
  slovakia("slovakia"),
  slovenia("slovenia"),
  southAfrica("south-africa"),
  southAfrica2("south-africa-2"),
  southKorea("south-korea"),
  spain("spain"),
  spainProvinces("spain-provinces"),
  sriLanka("sri-lanka"),
  sudan("sudan"),
  sweden("sweden"),
  switzerland("switzerland"),
  syria("syria"),
  taiwan("taiwan"),
  tajikistan("tajikistan"),
  thailand("thailand"),
  turkey("turkey"),
  uganda("uganda"),
  ukraine("ukraine"),
  unitedArabEmirates("united-arab-emirates"),
  unitedKingdom("united-kingdom"),
  unitedKingdomCounties("united-kingdom-counties"),
  uruguay("uruguay"),
  usa("usa"),
  usaAk("usa-ak"),
  usaAl("usa-al"),
  usaAllCounties("usa-all-counties"),
  usaAr("usa-ar"),
  usaAz("usa-az"),
  usaCa("usa-ca"),
  usaCanada("usa-canada"),
  usaCo("usa-co"),
  usaCt("usa-ct"),
  usaDe("usa-de"),
  usaFl("usa-fl"),
  usaFull("usa-full"),
  usaGa("usa-ga"),
  usaHi("usa-hi"),
  usaIa("usa-ia"),
  usaId("usa-id"),
  usaIl("usa-il"),
  usaIn("usa-in"),
  usaKs("usa-ks"),
  usaKy("usa-ky"),
  usaLa("usa-la"),
  usaMa("usa-ma"),
  usaMd("usa-md"),
  usaMe("usa-me"),
  usaMi("usa-mi"),
  usaMn("usa-mn"),
  usaMo("usa-mo"),
  usaMs("usa-ms"),
  usaMt("usa-mt"),
  usaNc("usa-nc"),
  usaNd("usa-nd"),
  usaNe("usa-ne"),
  usaNh("usa-nh"),
  usaNj("usa-nj"),
  usaNm("usa-nm"),
  usaNv("usa-nv"),
  usaNy("usa-ny"),
  usaOh("usa-oh"),
  usaOk("usa-ok"),
  usaOr("usa-or"),
  usaPa("usa-pa"),
  usaRi("usa-ri"),
  usaSc("usa-sc"),
  usaSd("usa-sd"),
  usaTn("usa-tn"),
  usaTx("usa-tx"),
  usaUt("usa-ut"),
  usaVa("usa-va"),
  usaVt("usa-vt"),
  usaWa("usa-wa"),
  usaWdc("usa-wdc"),
  usaWi("usa-wi"),
  usaWv("usa-wv"),
  usaWy("usa-wy"),
  uzbekistan("uzbekistan"),
  venezuela("venezuela"),
  vietnam("vietnam"),
  vietnamWithIslands("vietnam-with-islands"),
  world("world"),
  yemen("yemen"),
  zambia("zambia"),
  zimbabwe("zimbabwe");

  const MapEntity(this.filename);

  final String filename;

  static MapEntity getEnumFromCountryCode(String countryCode) {
    return switch (countryCode) {
      "AD" => MapEntity.andorra,
      "AO" => MapEntity.angola,
      "AR" => MapEntity.argentina,
      "AM" => MapEntity.armenia,
      "AU" => MapEntity.australia,
      "AT" => MapEntity.austria,
      "AZ" => MapEntity.azerbaijan,
      "BS" => MapEntity.bahamas,
      "BH" => MapEntity.bahrain,
      "BD" => MapEntity.bangladesh,
      "BY" => MapEntity.belarus,
      "BE" => MapEntity.belgium,
      "BT" => MapEntity.bhutan,
      "BO" => MapEntity.bolivia,
      "BA" => MapEntity.bosniaHerzegovina1,
      "BW" => MapEntity.botswana,
      "BR" => MapEntity.brazil,
      "BN" => MapEntity.bruneiDarussalam,
      "BG" => MapEntity.bulgaria,
      "BF" => MapEntity.burkinaFaso,
      "BI" => MapEntity.burundi,
      "KH" => MapEntity.cambodia,
      "CM" => MapEntity.cameroon,
      "CA" => MapEntity.canada,
      "CV" => MapEntity.capeVerde,
      "CF" => MapEntity.centralAfricanRepublic,
      "TD" => MapEntity.chad,
      "CL" => MapEntity.chile,
      "CN" => MapEntity.china,
      "CO" => MapEntity.colombia,
      "CG" => MapEntity.congo,
      "CD" => MapEntity.congoDr,
      "CR" => MapEntity.costaRica,
      "HR" => MapEntity.croatia,
      "CU" => MapEntity.cuba,
      "CY" => MapEntity.cyprus,
      "CZ" => MapEntity.czechRepublic,
      "DK" => MapEntity.denmark,
      "DJ" => MapEntity.djibouti,
      "DO" => MapEntity.dominicanRepublic,
      "EC" => MapEntity.ecuador,
      "EG" => MapEntity.egypt,
      "SV" => MapEntity.elSalvador,
      "EE" => MapEntity.estonia,
      "ET" => MapEntity.ethiopia,
      "FO" => MapEntity.faroeIslands,
      "FI" => MapEntity.finland,
      "FR" => MapEntity.france,
      "GE" => MapEntity.georgia,
      "DE" => MapEntity.germany,
      "GR" => MapEntity.greece,
      "GT" => MapEntity.guatemala,
      "GN" => MapEntity.guinea,
      "HT" => MapEntity.haiti,
      "HN" => MapEntity.honduras,
      "HK" => MapEntity.hongKong,
      "HU" => MapEntity.hungary,
      "IS" => MapEntity.iceland,
      "IN" => MapEntity.india,
      "ID" => MapEntity.indonesia,
      "IR" => MapEntity.iran,
      "IQ" => MapEntity.iraq,
      "IE" => MapEntity.ireland,
      "IL" => MapEntity.israel,
      "IT" => MapEntity.italy,
      "CI" => MapEntity.ivoryCoast,
      "JM" => MapEntity.jamaica,
      "JP" => MapEntity.japan,
      "KZ" => MapEntity.kazakhstan,
      "KE" => MapEntity.kenya,
      "XK" => MapEntity.kosovo,
      "KG" => MapEntity.kyrgyzstan,
      "LA" => MapEntity.laos,
      "LV" => MapEntity.latvia,
      "LI" => MapEntity.liechtenstein,
      "LT" => MapEntity.lithuania,
      "LU" => MapEntity.luxembourg,
      "MK" => MapEntity.macedonia,
      "MY" => MapEntity.malaysia,
      "ML" => MapEntity.mali,
      "MT" => MapEntity.malta,
      "MX" => MapEntity.mexico,
      "MD" => MapEntity.moldova,
      "ME" => MapEntity.montenegro,
      "MA" => MapEntity.morocco,
      "MZ" => MapEntity.mozambique,
      "MM" => MapEntity.myanmar,
      "NA" => MapEntity.namibia,
      "NP" => MapEntity.nepal,
      "NL" => MapEntity.netherlands,
      "NZ" => MapEntity.newZealand,
      "NI" => MapEntity.nicaragua,
      "NG" => MapEntity.nigeria,
      "NO" => MapEntity.norway,
      "OM" => MapEntity.oman,
      "PK" => MapEntity.pakistan,
      "PS" => MapEntity.palestine,
      "PA" => MapEntity.panama,
      "PY" => MapEntity.paraguay,
      "PE" => MapEntity.peru,
      "PH" => MapEntity.philippines,
      "PL" => MapEntity.poland,
      "PT" => MapEntity.portugal,
      "PR" => MapEntity.puertoRico,
      "QA" => MapEntity.qatar,
      "RO" => MapEntity.romania,
      "RU" => MapEntity.russia,
      "RW" => MapEntity.rwanda,
      "SM" => MapEntity.sanMarino,
      "SA" => MapEntity.saudiArabia,
      "RS" => MapEntity.serbia,
      "SL" => MapEntity.sierraLeone,
      "SG" => MapEntity.singapore,
      "SK" => MapEntity.slovakia,
      "SI" => MapEntity.slovenia,
      "ZA" => MapEntity.southAfrica,
      "KR" => MapEntity.southKorea,
      "ES" => MapEntity.spain,
      "LK" => MapEntity.sriLanka,
      "SD" => MapEntity.sudan,
      "SE" => MapEntity.sweden,
      "CH" => MapEntity.switzerland,
      "SY" => MapEntity.syria,
      "TW" => MapEntity.taiwan,
      "TJ" => MapEntity.tajikistan,
      "TH" => MapEntity.thailand,
      "TR" => MapEntity.turkey,
      "UG" => MapEntity.uganda,
      "UA" => MapEntity.ukraine,
      "AE" => MapEntity.unitedArabEmirates,
      "GB" => MapEntity.unitedKingdom,
      "UY" => MapEntity.uruguay,
      "US" => MapEntity.usa,
      "AK" => MapEntity.usaAk,
      "AL" => MapEntity.usaAl,
      "AR" => MapEntity.usaAr,
      "AZ" => MapEntity.usaAz,
      "CA" => MapEntity.usaCa,
      "CO" => MapEntity.usaCo,
      "CT" => MapEntity.usaCt,
      "DE" => MapEntity.usaDe,
      "FL" => MapEntity.usaFl,
      "GA" => MapEntity.usaGa,
      "HI" => MapEntity.usaHi,
      "IA" => MapEntity.usaIa,
      "ID" => MapEntity.usaId,
      "IL" => MapEntity.usaIl,
      "IN" => MapEntity.usaIn,
      "KS" => MapEntity.usaKs,
      "KY" => MapEntity.usaKy,
      "LA" => MapEntity.usaLa,
      "MA" => MapEntity.usaMa,
      "MD" => MapEntity.usaMd,
      "ME" => MapEntity.usaMe,
      "MI" => MapEntity.usaMi,
      "MN" => MapEntity.usaMn,
      "MO" => MapEntity.usaMo,
      "MS" => MapEntity.usaMs,
      "MT" => MapEntity.usaMt,
      "NC" => MapEntity.usaNc,
      "ND" => MapEntity.usaNd,
      "NE" => MapEntity.usaNe,
      "NH" => MapEntity.usaNh,
      "NJ" => MapEntity.usaNj,
      "NM" => MapEntity.usaNm,
      "NV" => MapEntity.usaNv,
      "NY" => MapEntity.usaNy,
      "OH" => MapEntity.usaOh,
      "OK" => MapEntity.usaOk,
      "OR" => MapEntity.usaOr,
      "PA" => MapEntity.usaPa,
      "RI" => MapEntity.usaRi,
      "SC" => MapEntity.usaSc,
      "SD" => MapEntity.usaSd,
      "TN" => MapEntity.usaTn,
      "TX" => MapEntity.usaTx,
      "UT" => MapEntity.usaUt,
      "VA" => MapEntity.usaVa,
      "VT" => MapEntity.usaVt,
      "WA" => MapEntity.usaWa,
      "WDC" => MapEntity.usaWdc,
      "WI" => MapEntity.usaWi,
      "WV" => MapEntity.usaWv,
      "WY" => MapEntity.usaWy,
      "UZ" => MapEntity.uzbekistan,
      "VE" => MapEntity.venezuela,
      "VN" => MapEntity.vietnam,
      "WORLD" => MapEntity.world,
      "YE" => MapEntity.yemen,
      "ZM" => MapEntity.zambia,
      "ZW" => MapEntity.zimbabwe,
      String() => throw UnimplementedError(),
    };
  }
}
